### PR TITLE
Upgrade to spryker 2.30

### PR DESCRIPTION
**Pull request by tonyfahrion**
With PHP 7.1.17, NodeJS 10 and Debian Jessie

### CODE REVIEW

**Comment by fuhbar** [comment]
@tonyfahrion Your attempt of getting rid of `envsubst` delivers:

```
sed: 1: "s/__VOLUMES__/

    - / ...": unescaped newline inside substitute pattern
ERROR: Top level object in 'None' needs to be an object not '<class 'NoneType'>'.
```

**Comment by fuhbar** [comment]
Receiving the following the Twig exception: 

```
yves-phpfpm_1         | [2018-05-24 18:25:55] Yves.CRITICAL: Twig_Error_Runtime - An exception has been thrown during the rendering of a template ("count(): Parameter must be an array or an objec[72/3621]
plements Countable") in "@ProductRelation/partial/product_relation_carousel.twig" at line 19. in "/app/vendor/twig/twig/lib/Twig/Template.php::447" {"exception":"[object] (Twig_Error_Runtime(code: 0): An
exception has been thrown during the rendering of a template (\"count(): Parameter must be an array or an object that implements Countable\") in \"@ProductRelation/partial/product_relation_carousel.twig\"
 at line 19. at /app/vendor/twig/twig/lib/Twig/Template.php:447, ErrorException(code: 0): count(): Parameter must be an array or an object that implements Countable at /app/vendor/spryker/product-label/sr
c/Spryker/Client/ProductLabel/Storage/ProductAbstractRelationReader.php:55)
yves-phpfpm_1         | [stacktrace]
yves-phpfpm_1         | #0 /app/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)
yves-phpfpm_1         | #1 /app/vendor/twig/twig/lib/Twig/Template.php(411): Twig_Template->display(Array)
yves-phpfpm_1         | #2 /app/vendor/twig/twig/lib/Twig/Environment.php(363): Twig_Template->render(Array)
yves-phpfpm_1         | #3 /app/vendor/spryker/product-relation/src/Spryker/Yves/ProductRelation/Plugin/ProductRelationTwigServiceProvider.php(71): Twig_Environment->render('@ProductRelatio...', Array)
yves-phpfpm_1         | #4 /app/cache/DE/Yves/twig/b2/b2a53be0f72fd7e3d46f2f8e2d50fa1c89251bb966f33742fe6a8acf387655a8.php(446): Spryker\\Yves\\ProductRelation\\Plugin\\ProductRelationTwigServiceProvider-
>Spryker\\Yves\\ProductRelation\\Plugin\\{closure}('related-product...', Array, 'Similar product...', '@ProductRelatio...')
yves-phpfpm_1         | #5 /app/vendor/twig/twig/lib/Twig/Template.php(215): __TwigTemplate_c82488ca6bb636a54e6c5f8695a5fb58df3672e71c5d07ff3effce93ef8dbb60->block_content(Array, Array)
yves-phpfpm_1         | #6 /app/cache/DE/Yves/twig/d1/d18fe5168ccd65362eb8fe147912a66c8f48f8515c2484612446b25fa27cfdc8.php(178): Twig_Template->displayBlock('content', Array, Array)
yves-phpfpm_1         | #7 /app/vendor/twig/twig/lib/Twig/Template.php(215): __TwigTemplate_9890d12908ade71d1b8e22ba98c6e9c76dde910c6e073c824138488a218897bf->block_page(Array, Array)
yves-phpfpm_1         | #8 /app/vendor/twig/twig/lib/Twig/Template.php(174): Twig_Template->displayBlock('page', Array, Array, false)
yves-phpfpm_1         | #9 /app/cache/DE/Yves/twig/b2/b2a53be0f72fd7e3d46f2f8e2d50fa1c89251bb966f33742fe6a8acf387655a8.php(39): Twig_Template->displayParentBlock('page', Array, Array)
yves-phpfpm_1         | #10 /app/vendor/twig/twig/lib/Twig/Template.php(215): __TwigTemplate_c82488ca6bb636a54e6c5f8695a5fb58df3672e71c5d07ff3effce93ef8dbb60->block_page(Array, Array)
yves-phpfpm_1         | #11 /app/cache/DE/Yves/twig/d1/d18fe5168ccd65362eb8fe147912a66c8f48f8515c2484612446b25fa27cfdc8.php(91): Twig_Template->displayBlock('page', Array, Array)
yves-phpfpm_1         | #12 /app/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_9890d12908ade71d1b8e22ba98c6e9c76dde910c6e073c824138488a218897bf->doDisplay(Array, Array)
yves-phpfpm_1         | #13 /app/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)
yves-phpfpm_1         | #14 /app/cache/DE/Yves/twig/b2/b2a53be0f72fd7e3d46f2f8e2d50fa1c89251bb966f33742fe6a8acf387655a8.php(29): Twig_Template->display(Array, Array)
yves-phpfpm_1         | #15 /app/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_c82488ca6bb636a54e6c5f8695a5fb58df3672e71c5d07ff3effce93ef8dbb60->doDisplay(Array, Array)
yves-phpfpm_1         | #16 /app/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)
yves-phpfpm_1         | #17 /app/vendor/twig/twig/lib/Twig/Template.php(411): Twig_Template->display(Array)
yves-phpfpm_1         | #18 /app/vendor/twig/twig/lib/Twig/Environment.php(363): Twig_Template->render(Array)
yves-phpfpm_1         | #19 /app/vendor/silex/silex/src/Silex/Application/TwigTrait.php(47): Twig_Environment->render('@Product/produc...', Array)
yves-phpfpm_1         | #20 /app/src/Pyz/Yves/Twig/Plugin/Provider/TwigServiceProvider.php(104): Spryker\\Shared\\Kernel\\Communication\\Application->render('@Product/produc...', Array)
yves-phpfpm_1         | #21 /app/src/Pyz/Yves/Twig/Plugin/Provider/TwigServiceProvider.php(69): Pyz\\Yves\\Twig\\Plugin\\Provider\\TwigServiceProvider->render(Array)
yves-phpfpm_1         | #22 [internal function]: Pyz\\Yves\\Twig\\Plugin\\Provider\\TwigServiceProvider->onKernelView(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent), 'k
ernel.view', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))
yves-phpfpm_1         | #23 /app/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent), 'kernel
.view', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))
yves-phpfpm_1         | #24 /app/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'kernel.view', Object(Symfony\\Component\\
HttpKernel\\Event\\GetResponseForControllerResultEvent))
yves-phpfpm_1         | #25 /app/vendor/symfony/http-kernel/HttpKernel.php(149): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('kernel.view', Object(Symfony\\Component\\HttpKernel\\Event\
\GetResponseForControllerResultEvent))
yves-phpfpm_1         | #26 /app/vendor/symfony/http-kernel/HttpKernel.php(64): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
yves-phpfpm_1         | #27 /app/vendor/silex/silex/src/Silex/Application.php(586): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
yves-phpfpm_1         | #28 /app/vendor/silex/silex/src/Silex/Application.php(563): Silex\\Application->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
yves-phpfpm_1         | #29 /app/public/Yves/index.php(25): Silex\\Application->run()
yves-phpfpm_1         | #30 {main}
```

**Comment by fuhbar** [comment]
Next bug: Piping the `docker-compose.yml` into the `docker-compose` causes problems on entering the container via the wrapper: 

```
./docker/run devel enter yves-phpfpm                                                                                                                 ✔
Executing: docker-compose -f /Users/fabian.doerk/Repos/github/claranet/spryker-demoshop/docker/docker-compose.yml -p spryker_dev exec yves-phpfpm /bin/bash
the input device is not a TTY
```

**Comment by tonyfahrion** [comment]
Okay, ready for another review session...

* the twig issue was due to an incompatibility with PHP 7.2.x; avoided by switching back to PHP 7.1.x
* the npm issue is now avoided by running `npm run yves` instead of prod builds via `npm run yves:prod`, the latter does not seem to work with the demoshop
* added multi-store support to local dev

**Pull request merged**
